const posts = [
  {featured:true,category:'AI INFRASTRUCTURE',date:'2026 — 08 — 28',title:'What I learned building a small GPU scheduler',excerpt:'A practical walk through queueing, fairness, and the quiet complexity behind making shared compute feel predictable.',tags:['GPU','Systems'],minutes:'8 min read'},
  {category:'ENGINEERING',date:'2026 — 08 — 14',title:'The useful parts of observability',excerpt:'Metrics tell you that something is wrong. Traces help you understand why.',tags:['Observability'],minutes:'6 min read'},
  {category:'AI INFRASTRUCTURE',date:'2026 — 07 — 30',title:'A mental model for inference serving',excerpt:'From request batching to token streaming: the pieces that shape latency in production.',tags:['Inference','LLM'],minutes:'10 min read'},
  {category:'FIELD NOTES',date:'2026 — 07 — 11',title:'Making peace with imperfect automation',excerpt:'Reliable tools are less about eliminating failure and more about making recovery obvious.',tags:['Automation'],minutes:'5 min read'},
  {category:'ENGINEERING',date:'2026 — 06 — 22',title:'Notes on designing for the next person',excerpt:'Some small decisions that make a codebase easier to inherit, operate, and improve.',tags:['Craft'],minutes:'4 min read'}
];
const list=document.querySelector('#postList'), featured=document.querySelector('#featuredPost'), search=document.querySelector('#searchInput');
const card=(p,hero=false)=>hero?`<article class="featured"><div class="post-meta"><span>${p.category}</span> · ${p.date} · ${p.minutes}</div><h3>${p.title}</h3><p>${p.excerpt}</p><a class="read-link" href="#">Read the note →</a></article>`:`<article class="post"><div class="post-meta"><span class="post-category">${p.category}</span>${p.date}<br />${p.minutes}</div><div><h3><a href="#">${p.title}</a></h3><p>${p.excerpt}</p><div class="tags">${p.tags.map(t=>`<span># ${t}</span>`).join('')}</div></div><div class="arrow">↗</div></article>`;
function render(items){const first=items.find(p=>p.featured); featured.innerHTML=first?card(first,true):''; list.innerHTML=items.filter(p=>!p.featured).map(p=>card(p)).join('')||'<p class="empty">No notes found. Try another search.</p>'}
render(posts);
search.addEventListener('input',()=>{const q=search.value.toLowerCase().trim();render(posts.filter(p=>`${p.title} ${p.excerpt} ${p.category} ${p.tags}`.toLowerCase().includes(q)))})
const topicCounts={"AI infrastructure":2,"Engineering":2,"Observability":1,"Inference":1,"Automation":1};document.querySelector('#topicList').innerHTML=Object.entries(topicCounts).map(([name,count])=>`<button class="topic" data-topic="${name}"><strong>${name}</strong><small>${String(count).padStart(2,'0')} notes ↗</small></button>`).join('');document.querySelectorAll('[data-topic]').forEach(b=>b.addEventListener('click',()=>{search.value=b.dataset.topic;search.dispatchEvent(new Event('input'));document.querySelector('#posts').scrollIntoView()}));
const theme=document.querySelector('#themeToggle');if(localStorage.theme==='dark')document.documentElement.classList.add('dark');theme.addEventListener('click',()=>{document.documentElement.classList.toggle('dark');localStorage.theme=document.documentElement.classList.contains('dark')?'dark':'light'});document.querySelector('#menuToggle').addEventListener('click',()=>document.querySelector('.desktop-nav').classList.toggle('mobile-open'));
